### ISSUE TITLE
KeyError: 'Traceback (most recent call last):\n 

### ISSUE THREAD

**Issue by liufangcen** [danieljf24/dual_encoding#2]
I am very interested in your work and thank you for the code.But in the process of running the code, I encountered a problem that could not be solved, I hope you can give me some help：

Traceback (most recent call last):
  File "/data/projects/zero-simple2/trainer.py", line 422, in <module>
    main()
  File "/data/projects/zero-simple2/trainer.py", line 215, in main
    train(opt, data_loaders['train'], model, epoch)
  File "/data/projects/zero-simple2/trainer.py", line 290, in train
    for i, train_data in enumerate(train_loader):
  File "/data/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/data/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/data/anaconda3/envs/pytorch/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/data/projects/zero-simple2/util/data_provider.py", line 107, in __getitem__\n    caption.append(self.vocab(\'<start>\'))\n  File "/data/projects/zero-simple2/util/vocab.py", line 34, in __call__\n    return self.word2idx[word]\nKeyError: \'<start>\'\n'

thank you very much!

**Comment by danieljf24** [comment]
What is the version of python and pytorch you used?

**Comment by liufangcen** [comment]
python==2.7.13
torch==0.3.1
